[package]
name = "hyperlisp"
version = "0.1.0"
authors = ["curlpipe <11898833+curlpipe@users.noreply.github.com>"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
ezcli = "0.3.4"
pest = "2.1.3"
pest_derive = "2.1.0"
